[package]
name = "acme-redirect"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
acme-micro = "0.8"
structopt = "0.3.14"
anyhow = "1.0.28"
env_logger = "0.7.1"
log = "0.4.8"
serde = "1.0.106"
toml = "0.5.6"
actix-web = "2.0.0"
actix-rt = "1.1.0"
openssl = "0.10.29"
time = "0.1"
colored = "1.9.3"
